-- Additive v2 records. The existing dsd_cases and smile-ai remain unchanged.
create table public.dsd_workspaces (
  id uuid primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  body jsonb not null,
  revision integer not null default 1 check (revision > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_assist_at timestamptz,
  constraint workspace_shape check (
    jsonb_typeof(body) = 'object' and body ?& array['schemaVersion','id','ownerId','name','photos','createdAt','updatedAt','activePhotoId','presets','consent']
    and body->'schemaVersion' = '1'::jsonb
    and body->>'id' = id::text and body->>'ownerId' = owner_id::text
    and jsonb_typeof(body->'photos') = 'array' and jsonb_array_length(body->'photos') <= 100
    and jsonb_typeof(body->'name') = 'string' and length(body->>'name') between 1 and 120
    and octet_length(body::text) <= 2097152
  ),
  constraint no_embedded_media check (
    not jsonb_path_exists(body, '$.**.base64') and not jsonb_path_exists(body, '$.**.data')
    and not jsonb_path_exists(body, '$.**.dataUrl') and not jsonb_path_exists(body, '$.**.imageData')
    and body::text !~ 'data:image/'
  )
);
comment on table public.dsd_workspaces is 'Owner-scoped Smile Studio v2 structured records. Photo and generated bytes are local only.';
create index dsd_workspaces_owner_updated on public.dsd_workspaces(owner_id, updated_at desc);
alter table public.dsd_workspaces enable row level security;
create policy workspaces_select_own on public.dsd_workspaces for select to authenticated using ((select auth.uid())=owner_id);
create policy workspaces_insert_own on public.dsd_workspaces for insert to authenticated with check ((select auth.uid())=owner_id);
create policy workspaces_update_own on public.dsd_workspaces for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy workspaces_delete_own on public.dsd_workspaces for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.dsd_workspaces from anon, authenticated;
grant select, delete on public.dsd_workspaces to authenticated;
grant insert(id,owner_id,body,revision) on public.dsd_workspaces to authenticated;
grant update(body,revision) on public.dsd_workspaces to authenticated;

create function public.touch_smile_workspace() returns trigger language plpgsql set search_path='' as $$
begin
  if new.revision <> old.revision + 1 then raise exception 'Workspace revision must advance by one'; end if;
  new.updated_at=now(); return new;
end;
$$;
-- AI reservation updates its own column and must not advance the editor revision.
create trigger touch_smile_workspace before update of body,revision on public.dsd_workspaces for each row execute function public.touch_smile_workspace();

create function public.reserve_smile_assistance(workspace_id uuid,photo_id uuid,source_revision integer)
returns jsonb language plpgsql security definer set search_path='' as $$
declare entry public.dsd_workspaces; selected_photo jsonb;
begin
  select * into entry from public.dsd_workspaces where id=workspace_id and owner_id=(select auth.uid()) for update;
  if not found then raise exception 'Workspace unavailable' using errcode='42501'; end if;
  if entry.body->'consent' is null or entry.body->'consent'='null'::jsonb
    or (entry.body->'consent'->>'policyVersion') is distinct from '1'
    or (entry.body->'consent'->>'recordedBy') is distinct from auth.uid()::text
    or coalesce(length(entry.body->'consent'->>'recordedAt'),0)=0 then
    raise exception 'Patient AI consent is required' using errcode='42501';
  end if;
  select value into selected_photo from jsonb_array_elements(entry.body->'photos') where value->>'id'=photo_id::text;
  if selected_photo is null or (selected_photo->>'revision')::integer <> source_revision then
    raise exception 'Photo revision is outdated' using errcode='40001';
  end if;
  if entry.last_assist_at > now()-interval '15 seconds' then raise exception 'Wait 15 seconds between AI requests' using errcode='P0001'; end if;
  update public.dsd_workspaces set last_assist_at=now() where id=workspace_id;
  return selected_photo;
end;
$$;
revoke all on function public.reserve_smile_assistance(uuid,uuid,integer) from public, anon;
grant execute on function public.reserve_smile_assistance(uuid,uuid,integer) to authenticated;
